const { withGradleProperties } = require('@expo/config-plugins');

// "Error resolving plugin [id: 'com.facebook.react.settings'] > 25.0.2"
// means Gradle itself launched under JDK 25 — React Native's Gradle
// plugin requires exactly Java 17 for that settings-plugin resolution
// step and fails immediately if the JVM running Gradle isn't 17, no
// matter what compileSdkVersion/buildToolsVersion is set to.
//
// Which JVM Gradle uses to run itself is controlled by `org.gradle.java.home`
// in gradle.properties (see https://docs.gradle.org/current/userguide/build_environment.html)
// — it overrides whatever JAVA_HOME/PATH resolves to for that invocation,
// which is exactly what's needed here: Java 25 stays installed and on the
// system PATH untouched, but THIS project's Gradle always runs under 17.
//
// android/gradle.properties is regenerated by `expo prebuild`, so this is
// applied as a config plugin (via withGradleProperties) rather than a
// hand-edit, exactly like plugins/withForceCompileSdk.js — it survives
// every future prebuild instead of being wiped by one.
//
// NOTE: the JDK path below is machine-specific (the exact path reported
// in this project's build error, on this Windows machine). If this
// project is ever built on a different machine or in CI with Java 17
// installed somewhere else, update JAVA_17_HOME below to match.
const JAVA_17_HOME = 'C:/Program Files/Eclipse Adoptium/jdk-17.0.20.101-hotspot';
const PROPERTY_KEY = 'org.gradle.java.home';

function withGradleJavaHome(config) {
  return withGradleProperties(config, (config) => {
    config.modResults = config.modResults.filter((item) => !(item.type === 'property' && item.key === PROPERTY_KEY));
    config.modResults.push({ type: 'property', key: PROPERTY_KEY, value: JAVA_17_HOME });
    return config;
  });
}

module.exports = withGradleJavaHome;
